<?
$arTooltips = array(
	"MODE" => GetMessage("MODE_TIP"),
	"RETURN" => GetMessage("RETURN_TIP"),
	"FILTERTYPE" => GetMessage("FILTERTYPE_TIP"),
	"FILE_NAME" => GetMessage("FILE_NAME"),
	"IMAGE" => GetMessage("IMAGE_TIP"),
	"SAVE_DIR" => GetMessage("SAVE_DIR_TIP"),
	"WIDTH" => GetMessage("WIDTH_TIP"),
	"HEIGHT" => GetMessage("HEIGHT_TIP"),
	"BG" => GetMessage("BG_TIP"),
	"QUALITY" => GetMessage("QUALITY_TIP"),
	"ADD_WATERMARK" => GetMessage("ADD_WATERMARK_TIP"),
	"WATERMARK_PATH" => GetMessage("WATERMARK_PATH_TIP"),
	"WATERMARK_POSITION" => GetMessage("WATERMARK_POSITION_TIP"),
	"ADD_CORNER" => GetMessage("ADD_CORNER_TIP"),
	"CORNER_PATH" => GetMessage("CORNER_PATH_TIP"),
	"ADD_TEXT" => GetMessage("ADD_TEXT_TIP"),
	"TEXT" => GetMessage("TEXT_TIP"),
	"TEXT_SIZE" => GetMessage("TEXT_SIZE_TIP"),
	"TEXT_COLOR" => GetMessage("TEXT_COLOR_TIP"),
	"TEXT_Y" => GetMessage("TEXT_Y_TIP"),
	"TEXT_X" => GetMessage("TEXT_X_TIP"),
	"TEXT_POSITION" => GetMessage("TEXT_POSITION_TIP"),
	"TEXT_ANGLE" => GetMessage("TEXT_ANGLE_TIP"),
	"FONT_PATH" => GetMessage("FONT_PATH_TIP"),
	"RESIZE_SMALL" => GetMessage("RESIZE_SMALL"),
	"CACHE_IMAGE" => GetMessage("CACHE_IMAGE_TIP"),
	"DEBUG" => GetMessage("DEBUG_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
	"CACHE_FILTER" => GetMessage("CACHE_FILTER_TIP"),	
);
?>